apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260520-200224-b0wcojt661mv-service
spec:
  selector:
    app: enterprise-system-20260520-200224-b0wcojt661mv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
